Flutter3 Upgrade + Splash Screen
zap-me/alloy pull request #17
Opened 2022-05-16 02:55 UTC by 4855062503

2022-05-16 22:31 UTC, djpnewton commented
CI is failling

2022-05-16 22:45 UTC, djpnewton requested changes
also in general:
*dont* put tabs into files that are *already* using spaces

2022-05-16 22:45 UTC, djpnewton commented on .github/workflows/flutter.yml
> +          flutter-version: '3.0'
better to use 3.0.x so it picks up bug fixes

2022-05-16 22:45 UTC, djpnewton commented on lib/config.dart
> +			String serverUrl = location.origin ?? '';
redeclearing `serverUrl` means that BeServerLocationOverrides will no longer work

2022-05-16 22:45 UTC, djpnewton commented on lib/main.dart
> -          colorScheme: ColorScheme(
lets not update the color scheme just yet, (just do the splash

2022-05-16 23:25 UTC, 4855062503 commented
@djpnewton

Replaced `lib/config.dart` & `lib/main.dart` with the ones in your master branch but still getting flutter build errors in CI

2022-05-17 00:26 UTC, 4855062503 commented
Just realized I still have to make the splash page mobile friendly.

2022-05-17 02:15 UTC, merged