New UI implementation (Login, Signup, Account Page)
zap-me/alloy pull request #18
Opened 2022-05-19 23:38 UTC by 4855062503

Continuing to update this PR, and fix Build error

2022-05-20 01:42 UTC, djpnewton commented
you have conflicts because you (*again*) did not start a new branch and have commits in this branch that were already squashed and applied in a previous PR

2022-05-20 02:19 UTC, 4855062503 commented
> new branch and have commits in this branch that were already squashed and applied in a previous PR

Will fix this.

2022-05-25 23:31 UTC, djpnewton requested changes
use the freezed libary to avoid using `dynamic` (see beryllium.dart)

remove the SFpro font (font already set to poppins on master)

rename accountForm.dart to account_form.dart like other files in the project

2022-05-25 23:31 UTC, djpnewton commented on pubspec.yaml
> +fonts:
remove this font, we will just use Poppins (also remove the added font file)

2022-05-25 23:31 UTC, djpnewton commented on lib/main.dart
> +      fontFamily: 'SF-Pro',
remove this line

2022-05-25 23:31 UTC, djpnewton commented on lib/main.dart
> +      colorScheme: ColorScheme.dark(primary: Color(0xFF1B1C25)),
remove this I have already set the basic theme colors on master

2022-05-25 23:31 UTC, djpnewton commented on lib/main.dart
> +    dynamic login;
dont use dynamic make a custom `@freezed` class

2022-05-30 04:28 UTC, 4855062503 commented
Still working on the Freezed stuff. Hopefully implemented by tonight.

2022-06-02 22:29 UTC, djpnewton requested changes
-restore old logo up top (add new logo for the login pages only)
- remove font file

2022-06-02 22:29 UTC, djpnewton commented on pubspec.yaml
> -  # fonts:
remove unecesary changes

2022-06-02 22:29 UTC, djpnewton commented on web/index.html
> +
unessesary change

2022-06-06 22:57 UTC, djpnewton commented
When loading with invalid auth I end up on this page (note the "reset" button looks odd):
![image](https://user-images.githubusercontent.com/42459/172262625-e067f15a-09ed-4cd9-bdeb-2a63292e2179.png)
![image](https://user-images.githubusercontent.com/42459/172262659-7c9aa4c5-ed99-47b7-a855-cae3eae1bed4.png)

2022-06-06 22:58 UTC, djpnewton commented
merged from master

2022-06-09 03:36 UTC, djpnewton commented
- [ ] lets make the signup page look closer to the original brief (remove the profile image widget, add in the large logo etc)
- [ ] remove the lost password from first screen (only have it on the login screen)
- [ ] move the "hey there lets get started" from the first screen and onto the register screen (like the design brief)
- [ ] add the "----- Or -----" from the design brief onto the login and register screens
- [ ] make the grey buttons the same grey (some or different shades of grey)

2022-06-09 22:52 UTC, djpnewton commented
couple of issues 

- on pixel 5:
![image](https://user-images.githubusercontent.com/42459/172958082-0394b29b-37cf-4891-99e6-e72c10782905.png)


- initial page says "Register" but other pages say "Create an Account", lets use "Create an Account" everywhere

2022-06-12 00:15 UTC, djpnewton commented
@4855062503 I tidied up the code a bit see the latest commit

-move everything related to login/registration to `login.dart`
-move some more repeated widget code to `widgets.dart`
-changed logic flow to use two new freezed enums (`LoginChoice` and `LoginResult`) 
this way we can use recursion to most of the descsions about what to do next in `_processLoginChoice()`

NB. still want to get rid of the `BeforeLoginForm_KillMe` screen and go strait to the register screen

2022-06-12 08:28 UTC, djpnewton commented
I removed the changes to exchange.dart and withdrawal.dart, I think these should go in a separate PR/branch:
[exchange_withdrawal.diff.txt](https://github.com/zap-me/alloy/files/8885475/exchange_withdrawal.diff.txt)

@4855062503 
There is only one thing left to do I think here is how can we go directly to the account creation screen and get rid of the `BeforeLoginForm_KillMe` screen. 

Once that is done you just need to test the following scenarios with and without 2FA:

- [ ] login
- [ ] login failure (invalid credentials, ie use the reset button)
- [ ] login failure (network error, fix network and retry)
- [ ] register
- [ ] recover account with email

2022-06-13 05:17 UTC, djpnewton commented
ok this is ready for testing now

2022-06-13 05:48 UTC, 4855062503 commented
@djpnewton 
✅ = test went as expected
> login w/out 2FA ✅
> signup w/out matching passwords ✅ (note: form validation text is not centered)
> signup w/ weak password ❔ - get "authorization error"
> signup w/ strong password & new email ❌  - get "authorization error"
> login w/ incorrect credentials ✅
> signup with existing email ✅ (note: could tell user that the email exists instead of throwing 'authorization error')
> login failure (invalid credentials, ie use the reset button) ✅
>  login failure (network error, fix network and retry) ✅ (note: no offline service workers exist, so upon a page refresh, get dinosaur Chrome network page. Some assets fail to load without network, if staying in the app long enough, network error alert pops up notifying user)
> recover account w/ email ✅ (note: permissions modal still pops up when link clicked)
> try recover account w/ nonemail (e.g. enter invalid input) ✅ (fails)
> try recover account with legit email which doesn't exist ❌ - doesn't warn user that their email doesn't exist, just has spinning modal waiting for confirmation

2022-06-13 07:02 UTC, merged