UI usability tweaks
zap-me/alloy pull request #30
Opened 2022-07-04 22:55 UTC by 4855062503

In reference to issue: https://github.com/zap-me/ops/issues/164

Changes:

    Remove 'sats' from BronzeValueInput widget LN withdrawals
    Pop withdrawal entry form once withdrawal complete for crypto withdrawals
    Pop deposit entry form once withdrawal complete for crypto deposits
    Change inconsistencies in invoice & recipient instances
    Add back button to Account2Account
    Add cancel button to 'choose your NZD deposit type' page

Will continue to test and update PR

2022-07-05 00:05 UTC, djpnewton requested changes

2022-07-05 00:05 UTC, djpnewton commented on lib/deposit.dart
> +    Navigator.pop(context);
We dont want this here. we want it after `MaterialPageRoute(
                builder: (context) => CryptoDepositNewScreen(widget.asset,
                    widget.l2Network, recipient, widget.websocket)))` (line 205/6) *IF* it was successful in creating a new deposit

2022-07-05 00:05 UTC, djpnewton commented on lib/withdrawal.dart
> +        Navigator.pop(context);
likewise this should be moved after `MaterialPageRoute(
                    builder: (context) => CryptoWithdrawalDetailScreen(
                        withdrawal, widget.websocket)))` (line 227/30) which only executes **if** the withdrawal was created

2022-07-05 07:10 UTC, djpnewton commented
instead of using the `didError` variable it would be nicer to do something like this:

```dart
res.when((withdrawal) async {
    await Navigator.push(context, MaterialPageRoute(builder:
       (context) => CryptoWithdrawalDetailScreen(withdrawal, widget.websocket)));
    Navigator.pop(context); // close form as we successfully created the withdrawal
  }, 
  error: (err) => alert(context, 'error', 'failed to create withdrawal (${BeError.msg(err)})'));
```

2022-07-05 22:53 UTC, djpnewton commented
> Hmmm, have tried this but doesn't pop off after withdrawal is completed.

works for me? I made an update, pull the branch.... we also want the same for deposits

2022-07-07 04:07 UTC, djpnewton commented
cool is this ready to test?

2022-07-07 04:17 UTC, 4855062503 commented
@djpnewton 

The `DepositAmountScreen` which holds the `BronzeValueInput` widget pops off as part of its Continue button:

https://github.com/zap-me/alloy/blob/66b17d5a7a61168a0f4c1b210c8bb87bad0cf9cd/lib/event.dart#L97

So regardless as to whether the deposit ends up being successful or a failure, it will pop of the stack.

If there's an error in setting an amount in the `BronzeValueInput`, the form validation won't let it pop off, until the user clicks Cancel.

This feels normal from a UX's POV.

Trying to figure out what I should change about this.

2022-07-07 07:55 UTC, djpnewton commented
> Trying to figure out what I should change about this.

You could try refactoring like so (in `class _CryptoDepositsScreenState`):
```dart
  Future<bool> _cryptoDeposit(Decimal amount) async {
    showAlertDialog(context, 'querying..');
    var res = await beCryptoDepositRecipient(
        widget.asset.symbol, widget.l2Network?.symbol, amount);
    Navigator.pop(context);
    return await res.when(
        (recipient, asset, l2Network) async {
          await Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => CryptoDepositNewScreen(widget.asset,
                    widget.l2Network, recipient, widget.websocket)));
          return true;
        }, error: (err) async {
          var msg = BeError.msg(err);
          snackMsg(context, widget.l2Network != null ? 'failed to create deposit: ${msg}' : 'failed to query deposit recipient: ${msg}',
            category: MessageCategory.Warning);
          return false;
        });
  }

  Future<void> _make() async {
    var amount = Decimal.zero;
    if (widget.l2Network != null) {
      var success = false;
      while (!success) {
        var amountStr = await Navigator.push<String>(
            context,
            MaterialPageRoute(
                builder: (context) => DepositAmountScreen(
                    widget.asset.symbol, widget.l2Network?.symbol)));
        if (amountStr == null) return;
        var amountDec = Decimal.tryParse(amountStr);
        if (amountDec == null || amountDec <= Decimal.zero) {
          snackMsg(context, 'invalid amount', category: MessageCategory.Warning);
          return;
        }
        amount = amountDec;
        amount = assetAmountFromUser(widget.asset.symbol, amount);
        success = await _cryptoDeposit(amount);
      }
    }
    else
      await _cryptoDeposit(amount);
  }
```
and do something similar for the fiat

2022-07-08 02:14 UTC, 4855062503 commented
I think this is OK for review now @djpnewton

2022-07-08 03:44 UTC, djpnewton commented
> and do something similar for the fiat

did you forget the fiat deposits?

2022-07-12 01:03 UTC, djpnewton approved these changes

2022-07-12 01:04 UTC, merged