Fix iOS Safari Font Issue
zap-me/alloy pull request #44
Opened 2022-08-09 03:43 UTC by 4855062503

Basically the dart `google_fonts` package is not suitable for iOS Safari, so it's best to import our own font into a fonts folder instead.

2022-08-09 03:59 UTC, djpnewton commented
Have you got a link to the issue?

2022-08-09 04:13 UTC, 4855062503 commented
[There were some people having similar problems in 2019](https://github.com/flutter/flutter/issues/41483).

But my fix came just by debugging:

- Checked network tab from phone debugging, google fonts loaded in Chrome browser (Desktop), Safari (Desktop), just not iOS Safari.
- Tried to change from GoogleFonts Poppin to a different GoogleFonts font, nothing changed
- Removed GoogleFonts instance, and replaced with local folder `fonts` font. Worked.

2022-08-09 10:32 UTC, djpnewton commented
It looks like you can just add the font to the assets and not change the dart code https://pub.dev/packages/google_fonts#font-bundling-in-assets

2022-08-10 05:02 UTC, 4855062503 commented
Will test this in the iOS simulator when I get home (left mac at home).

2022-08-11 02:01 UTC, 4855062503 commented
OK, have tested adding:

# To `pubspec.yaml`:
```yaml
assets:
  - google_fonts/Poppins-Regular.ttf
```
To `theme` in `lib/main.dart`

```dart
textTheme: GoogleFonts.poppinsTextTheme(),
```
This font loads correctly in my iOS simulator.

Is the font to be used Oxygen or Poppins?

2022-08-11 22:11 UTC, djpnewton commented
we are using poppins (see config.dart)

so it looks like you can just add the font to the assets:

and also add a note why we need to package the font directly rather then just letting the google package download it

```
assets:
  - google_fonts/Poppins-Regular.ttf
```

you can get rid of the other code changes no?

2022-08-12 01:37 UTC, 4855062503 commented
> you can get rid of the other code changes no?

If I don't manually add 

```dart
textTheme: GoogleFonts.poppinsTextTheme(),
```

then the fonts don't load in iOS Safari

2022-08-12 03:13 UTC, djpnewton requested changes

2022-08-12 03:13 UTC, djpnewton commented on lib/main.dart
> +      textTheme: GoogleFonts.poppinsTextTheme(),
```suggestion
      textTheme: ZapTextThemer(),
```

2022-08-12 03:13 UTC, djpnewton commented on lib/main.dart
> +import 'package:google_fonts/google_fonts.dart';
```suggestion
```

2022-08-12 03:13 UTC, djpnewton commented on pubspec.yaml
> +    # have to manually import google_fonts
you should explain *why* we need to manually package the font (eg. `if we do not package the font manually the google_fonts module fails to download the fonts on ios/safari see bug at https://xxx...`)

2022-08-12 04:17 UTC, djpnewton approved these changes
does it work?

2022-08-14 06:27 UTC, 4855062503 commented
> does it work?

Yup.

2022-08-14 22:35 UTC, merged

2022-08-15 03:44 UTC, djpnewton commented
reverted changes because of font color side effects
![image](https://user-images.githubusercontent.com/42459/184573584-9d986644-6766-4928-8704-ef787fea2bc0.png)
![image](https://user-images.githubusercontent.com/42459/184573597-9a42860c-5e3c-485b-af44-96e2e07b5d3c.png)
disapointing this didnt get caught in testing