Clear exchange input after an order has been made
zap-me/alloy pull request #68
Opened 2022-08-29 20:09 UTC by 4855062503

In reference to https://github.com/zap-me/ops/issues/191

2022-08-29 20:15 UTC, zap-janitor commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: 2eb83ca7225048df7993256ac9b331e97a0d72632122b5e216acf154a61fbd10 -->
🚀 Deployed on https://630d1e573e4a701f8a22251e--bitforge-test.netlify.app

2022-08-29 21:58 UTC, djpnewton requested changes
It would be more reliable to move these changes to just after we have succesfully created an order.

ie. just before we show the order screen

```Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => OrderScreen(order, widget.websocket)))
```

2022-08-29 22:22 UTC, 4855062503 commented
I considered that, but thought what if the user wanted to go back and edit the order by a small amount, and thought they may not want to rewrite the order entirely if the input was cleared.

But if you think it's better that way I'll change it.

2022-08-29 22:39 UTC, djpnewton commented
> I considered that, but thought what if the user wanted to go back and edit the order by a small amount, and thought they may not want to rewrite the order entirely if the input was cleared.
> 
> But if you think it's better that way I'll change it.

it only clears **after** an order is created . we are talking about in the `_exchange()` function once the "create order" button is clicked

2022-08-30 03:06 UTC, djpnewton requested changes

2022-08-30 03:06 UTC, djpnewton commented on lib/exchange.dart
>          (order) => Navigator.push(
you arent checking if the call was successful.

it needs to go in *this* block.

ie. **only** when the order was created successfully.

2022-08-30 04:04 UTC, djpnewton commented
need squash

2022-08-30 04:10 UTC, 4855062503 commented
@djpnewton 
Squashed.

2022-08-30 04:38 UTC, djpnewton approved these changes

2022-08-30 04:38 UTC, merged